from __future__ import annotations

from typing import List, Optional, Tuple

from dataclasses import dataclass

from Options import Toggle, OptionSet

from ..game import Game
from ..game_objective_template import GameObjectiveTemplate

from ..enums import KeymastersKeepGamePlatforms


HARD_DIFFICULTY_THRESHOLD: int = 5


@dataclass
class DragorrodsGrooveCoasterWaiWaiPartyArchipelagoOptions:
    dragorrods_groove_coaster_wai_wai_party_included_dlc: DragorrodsGrooveCoasterWaiWaiPartyIncludedDLC
    dragorrods_groove_coaster_wai_wai_party_include_mission_locked_songs: DragorrodsGrooveCoasterWaiWaiPartyIncludeMissionLockedSongs


class DragorrodsGrooveCoasterWaiWaiPartyGame(Game):
    name = "Dragorrod's Groove Coaster Wai Wai Party!!!!"
    platform = KeymastersKeepGamePlatforms.SW

    platforms_other = None

    is_adult_only_or_unrated = False

    options_cls = DragorrodsGrooveCoasterWaiWaiPartyArchipelagoOptions

    @property
    def included_dlc(self) -> set:
        return set(self.archipelago_options.dragorrods_groove_coaster_wai_wai_party_included_dlc.value)

    @property
    def include_mission_locked_songs(self) -> bool:
        return bool(self.archipelago_options.dragorrods_groove_coaster_wai_wai_party_include_mission_locked_songs.value)

    def _valid_songs(self, hard: bool) -> List[str]:
        included_dlc: set = self.included_dlc
        include_mission_locked: bool = self.include_mission_locked_songs

        valid: List[str] = []

        for title, easy, pack, mission_locked in SONGS:
            is_hard: bool = easy >= HARD_DIFFICULTY_THRESHOLD

            if is_hard != hard:
                continue

            if pack is not None and pack not in included_dlc:
                continue

            if mission_locked and not include_mission_locked:
                continue

            valid.append(title)

        return valid

    def songs_easy(self) -> List[str]:
        return sorted(self._valid_songs(hard=False))

    def songs_hard(self) -> List[str]:
        return sorted(self._valid_songs(hard=True))

    def game_objective_templates(self) -> List[GameObjectiveTemplate]:
        return [
            GameObjectiveTemplate(
                label="Complete SONG",
                data={"SONG": (self.songs_easy, 1)},
                is_time_consuming=False,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Complete SONG",
                data={"SONG": (self.songs_hard, 1)},
                is_time_consuming=False,
                is_difficult=True,
                weight=1,
            ),
        ]


SONGS: List[Tuple[str, int, Optional[str], bool]] = [
    ('Lemon', 1, None, False),
    ('U.S.A', 1, None, False),
    ('POP TEAM EPIC', 2, None, False),
    ('シュガーソングとビターステップ sugar song and bitter step', 2, None, False),
    ("残酷な天使のテーゼ A Cruel Angel's Thesis", 4, None, False),
    ('創聖のアクエリオン genesis of aquarion', 1, None, False),
    ('ETERNAL BLAZE', 2, None, False),
    ('空色デイズ Sky blue Days', 4, None, False),
    ('ようこそジャパリパークへ Welcome to japari park', 2, None, False),
    ('ただ君に晴れ Cloudless', 1, None, False),
    ('シャルル Charles', 2, None, False),
    ('ドラマツルギー dramaturgy', 2, None, False),
    ('すーぱーぬこになりたい I Want to Be a super Nuko', 3, None, False),
    ('ヒューマノイド Humanoid', 2, None, False),
    ('ミライトミライ Mirai to Mirai', 2, None, False),
    ('ヒトガタ Hitogata', 2, None, False),
    ('The Light', 1, None, False),
    ('AIAIAI', 2, None, False),
    ('キラメキライダー☆ Kirameki Rider', 1, None, False),
    ('REFLECT', 2, None, False),
    ('Prism Melody', 2, None, False),
    ('Journey Like a Thousand Years', 2, None, False),
    ('Shiny Smily Story (2022 ver.)', 2, None, False),
    ('Our Bright Parade', 4, None, False),
    ('全力ジャンピング！', 2, None, False),
    ('REALITY FANTASY', 2, None, False),
    ('ハジメテノオト The First Sound', 3, None, False),
    ('チュルリラ・チュルリラ ・ダッダッダ！ Chururira Chururira Daddadda!', 4, None, True),
    ('裏表ラバーズ Two-Sided Lovers', 2, None, False),
    ('ハロ／ハワユ Hello/How Are You', 1, None, False),
    ('ハッピーシンセサイザ Happy Synthesizer', 2, None, False),
    ('からくりピエロ Clockwork Clown', 1, None, False),
    ('千本桜 Thousand Cherry Blossoms', 2, None, False),
    ('Bad ∞ End ∞ Night', 3, None, False),
    ('Tell Your World', 2, None, False),
    ('六兆年と一夜物語 Six Trillion Years and One Nught Story', 4, None, True),
    ('脳漿炸裂ガール Brain Fluid Explosion Girl', 3, None, False),
    ("ロストワンの号哭 Lost One's Weeping", 3, None, False),
    ('ウミユリ海底譚 Tale of the Deep-sea Lily', 2, None, False),
    ('ECHO', 2, None, False),
    ('アスノヨゾラ哨戒班 Night Sky Patrol of Tomorrow', 3, None, False),
    ('ゴーストルール Ghost Rule', 3, None, False),
    ('*ハロー、プラネット *Hello, Planet', 2, None, False),
    ('腐れ外道とチョコレゐト Rotten Heresy and Chocolate', 4, None, True),
    ('砂の惑星 DUNE', 2, None, False),
    ('太陽系デスコ Solar System Disco', 2, None, False),
    ('Seyana.～何でも言うことを 聞いてくれるアカネチャン～ Akane chan Will Listen to Whatever You Have to Say', 1, None, False),
    ('ロキ ROKI', 2, None, False),
    ('METEOR', 1, None, True),
    ('グリーンライツ・セレナーデ Greenlights Serenade', 2, None, False),
    ('劣等上等 BRING IT ON', 2, None, False),
    ('アンドロイドガール Android Girl', 2, None, True),
    ('チルドレンレコード Children Record', 4, None, False),
    ('おねがいダーリン Please Darling', 2, None, False),
    ('LOVE FOR YOU', 2, None, False),
    ("待チ人ハ来ズ。 My Awaited Won't Come", 1, None, False),
    ('揺蕩うLove (feat. らっぷびと) Tayutau Love (feat. Rapbit)', 2, None, False),
    ('Bad Apple!! feat.nomico', 2, None, False),
    ('魔理沙は大変なもの を盗んでいきました Marisa Stole the Precious Thing', 2, None, False),
    ('ゆけむり魂温泉 Streamy Soul Hot-Springs', 2, None, False),
    ('あうんどばいみー Aund By Me', 3, None, False),
    ("聖少女サクリファイス Sacred Girl's Sacrifice", 2, None, False),
    ('Captain Murasa [Tracy vs. Astronomical Mix]', 2, None, True),
    ('畢竟成仏 Finally Becoming a Buddha', 2, None, False),
    ('ナイト・オブ・ナイツ Night of Knights/Knight of Nights', 3, None, False),
    ('明星ロケット Venus Rocket', 2, None, False),
    ('taboo tears you up 2017 -GC EDIT-', 3, None, True),
    ('ジョーカー・ジュンコ ～ 永遠の純化 Joker Junko ~ Eienno Junka', 3, None, True),
    ('Metamorphosis', 2, None, False),
    ('Scream out!', 3, None, False),
    ('月に叢雲華に風 Clouds Over the Moon, and Wind Over the Flowers', 2, None, False),
    ('ID', 3, None, False),
    ('FEEL MY BEAT!', 3, None, False),
    ('FullMoon', 2, None, True),
    ('Garakuta Doll Play', 5, None, False),
    ("Don't Fight The Music", 4, None, False),
    ('影の伝説 ~豚乙女mix~ Kage No Densetsu -BUTAOTOME Mix-', 3, None, False),
    ('小夜のテーマ ～とぱぞのアレンジ～ Sayo No Theme ~t+pazolite Arrange~', 2, None, True),
    ('バブルボブルメドレー Bubble Bobble Medley', 4, None, False),
    ('バトル#2 ～ヒゲドライバーMIX～ Battle#2 -High Driver Mix-', 1, None, True),
    ('THE SEVENTH BOSS 2019 (GC Mix)', 1, None, False),
    ('ライトニング・デュアルホープ A Lightning Dual Hope (GC Mix)', 2, None, True),
    ('FAKE -PROGRESSIVE KOTA MIX- (GC Mix)', 3, None, False),
    ('The world of spirit', 2, None, False),
    ('Freedom', 2, None, True),
    ('Jack-the-Ripper◆', 5, None, True),
    ('While Shining feat. Yukacco', 2, None, False),
    ('Brain Power', 4, None, True),
    ('ouroVoros', 4, None, True),
    ('Party 4U ’’holy nite mix’’', 5, None, True),
    ('conflict', 3, None, False),
    ('AXION', 3, None, False),
    ('B.B.K.K.B.K.K.', 2, None, False),
    ('Tropics -GC edit-', 1, None, True),
    ('Halcyon', 3, None, False),
    ('LINK LINK FEVER!!!', 2, None, False),
    ('GROOVE LOOP', 1, None, False),
    ('An indignant world', 3, None, True),
    ('KUNG FU GIRL', 3, None, False),
    ("It's a pit world", 1, None, True),
    ('Shiva', 3, None, True),
    ('VOLT', 3, None, True),
    ('Cosmic Ray', 4, None, True),
    ('Got more raves?', 5, None, True),
    ('MERLIN', 4, None, True),
    ('Lost Colors', 1, None, False),
    ('飛び立て！ドリームパーティー Tobitate! DreamParty', 2, None, False),
    ('Horizons', 4, None, True),
    ('ADRENA', 3, None, True),
    ('君のStarlight Road Kimi no Starlight Road', 2, None, False),
    ('ﾃｯﾃｰﾃﾚ!ゲーミングデイズ！ tettetere! Gaming Days!', 2, None, False),
    ('Groove High', 1, None, False),
    ('God knows...', 2, 'Hit Song + VTuber Pack', False),
    ('only my railgun', 2, 'Hit Song + VTuber Pack', False),
    ('甲賀忍法帖 The Kōga Ninja Scrolls', 2, 'Hit Song + VTuber Pack', True),
    ('極楽浄土 Gokuraku Jodo', 1, 'Hit Song + VTuber Pack', False),
    ('夜に駆ける Yoru ni Kakeru', 2, 'Hit Song + VTuber Pack', False),
    ('ヒバリ Hibari', 2, 'Hit Song + VTuber Pack', False),
    ('Shiny Smily Story', 3, 'Hit Song + VTuber Pack', False),
    ('叩ケ 叩ケ 手ェ叩ケ Tatake Tatake Tee Tatake', 4, 'Hit Song + VTuber Pack', False),
    ('-A.I.D-', 2, 'Hit Song + VTuber Pack', False),
    ('夢見る空へ Yumemiru Sorae', 4, 'Hit Song + VTuber Pack', False),
    ('ハレ晴レユカイ Hare Hare Yukai', 2, 'Hit Song + VTuber Pack 2', False),
    ('コネクト Connect -TV MIX-', 3, 'Hit Song + VTuber Pack 2', False),
    ('DreamRiser', 2, 'Hit Song + VTuber Pack 2', False),
    ('fake town baby', 2, 'Hit Song + VTuber Pack 2', True),
    ('だから僕は音楽を辞めた Moonlight', 2, 'Hit Song + VTuber Pack 2', False),
    ('うっせぇわ Usseewa', 2, 'Hit Song + VTuber Pack 2', False),
    ('廻廻奇譚 Kaikai Kitan', 2, 'Hit Song + VTuber Pack 2', False),
    ('Mr.VIRTUALIZER', 2, 'Hit Song + VTuber Pack 2', False),
    ('失礼しますが、RIP♡ Excuse My Rudeness, But Could You Please RIP?', 1, 'Hit Song + VTuber Pack 2', False),
    ('HINOTORI', 1, 'Hit Song + VTuber Pack 2', False),
    ('LOVE!HUG!GROOVY!!', 2, 'D4DJ Groovy Mix + Game Song Pack', False),
    ('ぐるぐるDJ TURN!! Guru Guru DJ TURN!!', 3, 'D4DJ Groovy Mix + Game Song Pack', False),
    ('電乱★カウントダウン Electric Chaos★Countdown', 3, 'D4DJ Groovy Mix + Game Song Pack', False),
    ('Photon Melodies', 2, 'D4DJ Groovy Mix + Game Song Pack', False),
    ('バラライカ Balalaika', 4, 'D4DJ Groovy Mix + Game Song Pack', False),
    ('気分上々↑↑ Feeling Good ↑↑', 3, 'D4DJ Groovy Mix + Game Song Pack', False),
    ('CAPTAIN NEO ～BOSS SCENE1 (D4DJ MIX)', 2, 'D4DJ Groovy Mix + Game Song Pack', False),
    ('CHAOS ～BOSS SCENE 7 (D4DJ MIX)', 3, 'D4DJ Groovy Mix + Game Song Pack', False),
    ('DADDY MULK (D4DJ MIX)', 2, 'D4DJ Groovy Mix + Game Song Pack', True),
    ('URBAN TRAIL (D4DJ MIX)', 3, 'D4DJ Groovy Mix + Game Song Pack', False),
    ('Pray', 1, 'Hit Song + VTuber Pack 3', True),
    ('女々しくて Memeshikute', 2, 'Hit Song + VTuber Pack 3', False),
    ('全力バタンキュー Zenryoku Batankyu', 2, 'Hit Song + VTuber Pack 3', False),
    ('RDY', 1, 'Hit Song + VTuber Pack 3', False),
    ('アゲナゲン Again And Again', 4, 'Hit Song + VTuber Pack 3', False),
    ('怪物 Monster', 3, 'Hit Song + VTuber Pack 3', False),
    ('マイアングル My Angle', 2, 'Hit Song + VTuber Pack 3', False),
    ('オペレーション・ネバーランド Operation Neverland', 3, 'Hit Song + VTuber Pack 3', False),
    ('We Are Vox Monsters', 3, 'Hit Song + VTuber Pack 3', False),
    ('Second Sight Stella', 2, 'Hit Song + VTuber Pack 3', False),
    ('恋は渾沌の隷也 Koihakaosunoshimobenari', 1, 'Hit Song + VTuber Pack 4', False),
    ('チューリングラブ Turing Love feat.Sou', 2, 'Hit Song + VTuber Pack 4', False),
    ('阿修羅ちゃん Ashura-chan', 2, 'Hit Song + VTuber Pack 4', False),
    ('パメラ Pamela (self cover)', 3, 'Hit Song + VTuber Pack 4', False),
    ('残響散歌 Zankyosanka -TV version-', 1, 'Hit Song + VTuber Pack 4', False),
    ('A New Start', 2, 'Hit Song + VTuber Pack 4', False),
    ('Hello, Hologram', 3, 'Hit Song + VTuber Pack 4', False),
    ('毒の王子さま Doku no Oujisama', 2, 'Hit Song + VTuber Pack 4', False),
    ('アデュー、サロー adieu, Salauds', 2, 'Hit Song + VTuber Pack 4', False),
    ('毒杯スワロウ Swallow the venom', 3, 'Hit Song + VTuber Pack 4', True),
    ('飛んでK！ホロライブサマー Tonde K! Hololive Summer', 2, 'hololive Pack', True),
    ('浸食!! 地球全域全おーしゃん Domination! All the World Is an Ocean!', 3, 'hololive Pack', False),
    ('Q', 2, 'hololive Pack', False),
    ('鬼灯日和 Hozukibiyori', 2, 'hololive Pack', False),
    ('Over Time', 1, 'hololive Pack', False),
    ('PANIGHT', 1, 'hololive Pack', False),
    ('進め↑BAKATARATION Let’s Go! Bakataration', 2, 'hololive Pack', False),
    ('Rise', 1, 'hololive Pack', False),
    ('灼熱にて純情 syakunetsu nite junjou (wii-wii-woo)', 3, 'hololive Pack', False),
    ('Play Dice!', 3, 'hololive Pack', False),
    ("泥の分際で私だけの 大切を奪おうだなんて Being low as dirt, taking what's important from me", 4, 'Hit Song + VTuber Pack 5', True),
    ('Overdose', 2, 'Hit Song + VTuber Pack 5', False),
    ('カオスが極まる Chaos Ga Kiwamaru', 3, 'Hit Song + VTuber Pack 5', False),
    ('ちゅ、多様性。 Chu, tayousei', 2, 'Hit Song + VTuber Pack 5', False),
    ('アイドル Idol Anime Edit', 2, 'Hit Song + VTuber Pack 5', False),
    ('粛聖!! ロリ神レクイエム☆ SHUKUSEI!! RORI GAMI REKUIEMU☆', 3, 'Hit Song + VTuber Pack 5', False),
    ('夢見る羊 Dreamy sheep', 2, 'Hit Song + VTuber Pack 5', False),
    ("I'm Your Treasure Box ＊あなたは マリンせんちょうを たからばこからみつけた。 * You have found captain Marine in a treasure chest", 3, 'Hit Song + VTuber Pack 5', False),
    ('いいわけバニー Alibi Bunny', 3, 'Hit Song + VTuber Pack 5', False),
    ('WWW', 2, 'Hit Song + VTuber Pack 5', False),
    ('インドア系なら トラックメイカー Indoor Kei Nara Trackmaker', 1, 'Hit Song + VTuber Pack 6', True),
    ("あの世行きの バスに乗ってさらば。 I'm Getting on The Bus to The Other World, See ya!", 2, 'Hit Song + VTuber Pack 6', False),
    ('青のすみか Where Our Blue Is', 3, 'Hit Song + VTuber Pack 6', False),
    ('唱 Show', 1, 'Hit Song + VTuber Pack 6', False),
    ('勇者 The Brave', 3, 'Hit Song + VTuber Pack 6', False),
    ('Bling-Bang-Bang-Born', 3, 'Hit Song + VTuber Pack 6', False),
    ('スキスキ星人 Love Love Alien', 2, 'Hit Song + VTuber Pack 6', False),
    ('Stellar Stellar', 2, 'Hit Song + VTuber Pack 6', False),
    ('美少女無罪♡パイレーツ Bishoujyo Muzai♡Pirates', 3, 'Hit Song + VTuber Pack 6', False),
    ('愛包ダンスホール Heart Pie Dancehall', 2, 'Hit Song + VTuber Pack 6', False),
    ('Say!ファンファーレ! Say!Fanfare!', 2, 'hololive Pack 2', False),
    ('サクラカゼ Sakurakaze', 2, 'hololive Pack 2', False),
    ('My song', 3, 'hololive Pack 2', False),
    ('Red', 3, 'hololive Pack 2', False),
    ('カミサマ・ネコサマ KAMISAMA・NEKOSAMA', 3, 'hololive Pack 2', False),
    ('ばーちゃらぶ Virtualove', 2, 'hololive Pack 2', False),
    ('右左君君右下上目 きゅるんめちょかわ！ Right Left You You Puppy dog eyes Mecho kawaii !', 3, 'hololive Pack 2', False),
    ('ぎゅーどんかーにばる！ Gyu-Don Carnival!', 2, 'hololive Pack 2', False),
    ('瞬間ハートビート Shunkan Heartbeat', 1, 'hololive Pack 2', False),
    ('シンメトリー symmetry', 3, 'hololive Pack 2', True),
    ('ロミオとシンデレラ Romeo and Cinderella', 2, 'VOCALOID Pack', False),
    ('紅一葉 Crimson Leaf', 1, 'VOCALOID Pack', False),
    ('アブストラクト・ナンセンス Abstract Nonsense', 5, 'VOCALOID Pack', True),
    ('だんだん早くなる Getting Faster', 3, 'VOCALOID Pack', False),
    ('フィクサー Fixer', 2, 'VOCALOID Pack', False),
    ('テオ Teo', 3, 'VOCALOID Pack', False),
    ('アンノウン・マザーグース Unknown Mother-Goose', 2, 'VOCALOID Pack', False),
    ('リバースユニバース Reverse Universe', 3, 'VOCALOID Pack', False),
    ('だれかの心臓になれたなら I want to be in your heart', 3, 'VOCALOID Pack', False),
    ('アカリがやってきたぞっ Akari has Arrived', 3, 'VOCALOID Pack', False),
    ('悪ノ娘 The Princess of Lucifer', 2, 'VOCALOID Pack 2', False),
    ('初音ミクの消失 THE END OF HATSUNE MIKU', 5, 'VOCALOID Pack 2', False),
    ('サンドリヨン Cendrillon', 2, 'VOCALOID Pack 2', False),
    ('炉心融解 Meltdown', 1, 'VOCALOID Pack 2', False),
    ('ネトゲ廃人シュプレヒコール The MMORPG ADDICTS ANTHEM', 2, 'VOCALOID Pack 2', False),
    ('いーあるふぁんくらぶ 12funclub', 2, 'VOCALOID Pack 2', False),
    ("幸せになれる 隠しコマンドがあるらしい It Seems Like There's A Secret Command To Becoming Happy", 2, 'VOCALOID Pack 2', False),
    ('アンドロメダアンドロメダ Andromeda Andromeda -Invade MIX-', 2, 'VOCALOID Pack 2', True),
    ('エイリアンエイリアン Alien Alien', 1, 'VOCALOID Pack 2', False),
    ('脱法ロック Law-evading Rock', 2, 'VOCALOID Pack 2', False),
    ('ミライ Future', 1, 'VOCALOID Pack 3', False),
    ('夜咄ディセイブ Night Tales Deceive', 3, 'VOCALOID Pack 3', False),
    ('Circuit DISCO', 1, 'VOCALOID Pack 3', False),
    ('Over Drive', 1, 'VOCALOID Pack 3', False),
    ('Perverse Love Rock!', 2, 'VOCALOID Pack 3', False),
    ('Conqueror', 2, 'VOCALOID Pack 3', False),
    ('アウターサイエンス Outer Science', 3, 'VOCALOID Pack 3', True),
    ('Into Starlight', 1, 'VOCALOID Pack 3', False),
    ('Reload', 2, 'VOCALOID Pack 3', False),
    ('てるみい Tell me', 3, 'VOCALOID Pack 3', False),
    ("ワールズエンド・ダンスホール World's End Dancehall", 2, 'VOCALOID Pack 4', False),
    ('ヤンキーボーイ・ヤンキーガール Yankee Boy Yankee Girl', 4, 'VOCALOID Pack 4', True),
    ('ちがう!!! We Are Different !!! (or Same)', 2, 'VOCALOID Pack 4', False),
    ('彗星ハネムーン Comet Honeymoon', 1, 'VOCALOID Pack 4', False),
    ('はやくそれになりたい！ I wanna be it !', 2, 'VOCALOID Pack 4', False),
    ('スーサイドパレヱド Suicide Parada', 2, 'VOCALOID Pack 4', False),
    ('ベノム Venom', 1, 'VOCALOID Pack 4', False),
    ('乙女解剖 Otome Kaibou', 1, 'VOCALOID Pack 4', False),
    ('絶対にチョコミントを食べる アオイチャン Zettai Ni Chocomint Wo Taberu Aoichan', 3, 'VOCALOID Pack 4', False),
    ('ヴィラン Villain', 1, 'VOCALOID Pack 4', False),
    ('悪ノ召使 Servant of Evil', 1, 'VOCALOID Pack 5', False),
    ('いろは唄 Iroha Uta', 2, 'VOCALOID Pack 5', False),
    ('Just Be Friends', 1, 'VOCALOID Pack 5', False),
    ('リモコン Remote Control', 4, 'VOCALOID Pack 5', False),
    ('天ノ弱 Amanojaku', 2, 'VOCALOID Pack 5', False),
    ('ドクター=ファンクビート Doctor=Funk beat', 3, 'VOCALOID Pack 5', True),
    ('39みゅーじっく！ 39 Music!', 1, 'VOCALOID Pack 5', False),
    ('脱獄 Jailbreak', 3, 'VOCALOID Pack 5', False),
    ('ジャンキーナイトタウン オーケストラ Junky Night Town Orchestra', 2, 'VOCALOID Pack 5', False),
    ('KING', 2, 'VOCALOID Pack 5', False),
    ('ココロ Kokoro', 1, 'VOCALOID Pack 6', False),
    ('ダブルラリアット Double Lariat', 1, 'VOCALOID Pack 6', False),
    ('ルカルカ★ナイトフィーバー Luka Luka★Night Fever', 3, 'VOCALOID Pack 6', True),
    ('飴と鎖 Ametokusari', 4, 'VOCALOID Pack 6', False),
    ('Crazy ∞ nighT', 3, 'VOCALOID Pack 6', False),
    ('どりーみんチュチュ Dreamin Chuchu', 2, 'VOCALOID Pack 6', False),
    ('ポジティブ☆ダンスタイム Positive Dance Time', 3, 'VOCALOID Pack 6', False),
    ('グッバイ宣言 Good-Bye Declaration', 3, 'VOCALOID Pack 6', False),
    ('ヴァンパイア The Vampire', 3, 'VOCALOID Pack 6', False),
    ('ぐるぐるめろメロディ♪ Groove Groove melo-melody♪', 3, 'VOCALOID Pack 6', False),
    ('ブレス・ユア・ブレス Bless Your Breath', 2, 'VOCALOID Pack 7', False),
    ('愛されなくても君がいる Because You’re Here', 1, 'VOCALOID Pack 7', False),
    ('初音天地開闢神話 Hatsune Creation Myth', 3, 'VOCALOID Pack 7', True),
    ('フューチャー・イヴ FUTURE EVE', 4, 'VOCALOID Pack 7', False),
    ('TODAY THE FUTURE', 3, 'VOCALOID Pack 7', False),
    ('Singularity', 1, 'VOCALOID Pack 7', False),
    ('ビートシンカー BEAT SYNCER', 2, 'VOCALOID Pack 7', False),
    ('ダーリンダンス Darling Dance', 1, 'VOCALOID Pack 7', False),
    ('シンデレラ Cinderella', 3, 'VOCALOID Pack 7', False),
    ('神っぽいな God-ish', 3, 'VOCALOID Pack 7', False),
    ('君色マリンスノウ Colorful Marine Snow', 2, 'VOCALOID Pack 8', False),
    ('SnowMix♪', 2, 'VOCALOID Pack 8', False),
    ('エゴロック EgoRock', 2, 'VOCALOID Pack 8', False),
    ('転生林檎 Reincarnation Apple', 3, 'VOCALOID Pack 8', False),
    ('霽れを待つ Hare wo matsu', 2, 'VOCALOID Pack 8', False),
    ('Nyanyanyanyanyanyanya!', 1, 'VOCALOID Pack 8', False),
    ('トリノコシティ Torinokocity', 3, 'VOCALOID Pack 8', False),
    ('PaⅢ.SENSATION', 3, 'VOCALOID Pack 8', False),
    ('クラブ＝マジェスティ Club=Majesty', 2, 'VOCALOID Pack 8', True),
    ('パラジクロロベンゼン Paradichlorobenzene', 1, 'VOCALOID Pack 8', False),
    ('ネクストネスト NEXT NEST', 2, 'VOCALOID Pack 9', False),
    ('Hand in Hand (Magical Mirai Ver.)', 2, 'VOCALOID Pack 9', False),
    ('HERO', 3, 'VOCALOID Pack 9', False),
    ('恋愛裁判 Love Trial', 1, 'VOCALOID Pack 9', False),
    ('少女レイ Shoujo Rei', 2, 'VOCALOID Pack 9', False),
    ('テレキャスタービーボーイ Telecaster b boy', 3, 'VOCALOID Pack 9', True),
    ('フォニイ phony', 3, 'VOCALOID Pack 9', False),
    ('Surges', 3, 'VOCALOID Pack 9', False),
    ('酔いどれ知らず An Unaware Drunk', 2, 'VOCALOID Pack 9', False),
    ('強風オールバック Kyoufuu Ooru Bakku', 1, 'VOCALOID Pack 9', False),
    ('ヒトリシズカ Hitorishizuka', 2, 'Touhou Project Arrangements Pack 1', False),
    ("チルノのパーフェクト さんすう教室 Cirno's Perfect Math Class", 4, 'Touhou Project Arrangements Pack 1', False),
    ('焼痕煉黑、冷艶ノ絶 Burnt Black, the End of Frozen Beauty', 3, 'Touhou Project Arrangements Pack 1', False),
    ("エピクロスの虹は もう見えない Epicurus' Rainbow Can No Longer Be Seen", 1, 'Touhou Project Arrangements Pack 1', False),
    ('7 days a week', 2, 'Touhou Project Arrangements Pack 1', False),
    ('メイドと血の懐中時計 The Maid and the Pocket Watch of Blood', 3, 'Touhou Project Arrangements Pack 1', False),
    ('tete+a+tete', 4, 'Touhou Project Arrangements Pack 1', False),
    ('悪戯センセーション Mischievous Sensation', 5, 'Touhou Project Arrangements Pack 1', False),
    ('そして誰もいなくなった And Then There Were None', 1, 'Touhou Project Arrangements Pack 1', False),
    ('最終鬼畜妹 フランドール・S Saishuu Kichiku Imouto Flandre S', 3, 'Touhou Project Arrangements Pack 1', True),
    ('クリスタライズ！ Cristalize!', 2, 'Touhou Project Arrangements Pack 2', False),
    ('IN MY LIFE', 1, 'Touhou Project Arrangements Pack 2', False),
    ('DOWN DOWN DOLL', 2, 'Touhou Project Arrangements Pack 2', False),
    ('My Voice is Dead.', 4, 'Touhou Project Arrangements Pack 2', False),
    ('Colors', 2, 'Touhou Project Arrangements Pack 2', False),
    ('二つの魂を剣に託して Hutatsu No Tamashi Wo Tsurugi Ni Takushite', 2, 'Touhou Project Arrangements Pack 2', False),
    ('無邪気と言う名の正義 The Justice Called "Innocence"', 2, 'Touhou Project Arrangements Pack 2', False),
    ('蒼空に舞え、墨染の桜 Dance in the Blue Sky, Ink Black Cherry Blosom', 1, 'Touhou Project Arrangements Pack 2', False),
    ('Border of Colour', 2, 'Touhou Project Arrangements Pack 2', False),
    ('弾・幕・決・壊 Dan.Maku.Ke.Kai', 4, 'Touhou Project Arrangements Pack 2', True),
    ('Finder', 2, 'Touhou Project Arrangements Pack 3', False),
    ('ジンガイクライシス JINGAI CRISIS', 3, 'Touhou Project Arrangements Pack 3', False),
    ('響縁 Echoed Bonds', 3, 'Touhou Project Arrangements Pack 3', False),
    ('ぐる☆ネーション Guru ☆ Nation', 2, 'Touhou Project Arrangements Pack 3', False),
    ('バブルの呪文はシュー！ ポッ！プッシュ！ Bubble no Jumon ha Shu! Po! Push!', 2, 'Touhou Project Arrangements Pack 3', False),
    ('シンデレラケージ Cinderella Cage', 1, 'Touhou Project Arrangements Pack 3', False),
    ('幻想の旅人へ ～ Catch the Heart Gensouno tabibitohe ~ Catch the Heart', 1, 'Touhou Project Arrangements Pack 3', False),
    ('Help me, ERINNNNNN!!', 1, 'Touhou Project Arrangements Pack 3', False),
    ('泡沫、哀のまほろば Ephemeral, Great and Splendid Land of Grief', 1, 'Touhou Project Arrangements Pack 3', False),
    ('SACRIFICE feat. ayame (GC REFIX)', 3, 'Touhou Project Arrangements Pack 3', True),
    ('1/8000000', 2, 'Touhou Project Arrangements Pack 4', False),
    ('GROOVE IT LUCKY (GC Mix)', 3, 'Touhou Project Arrangements Pack 4', False),
    ('色は匂へど 散りぬるを Iro wa Nioedo Chirinuru wo (Fractal 1.5 ver)', 1, 'Touhou Project Arrangements Pack 4', False),
    ('人間が大好きな こわれた妖怪の唄 Ningen ga Daisuki na Kowareta Youkai no Uta', 1, 'Touhou Project Arrangements Pack 4', False),
    ('清らかな幸福 Kiyoraka na Koufuku', 3, 'Touhou Project Arrangements Pack 4', False),
    ('天狗の詫び証文 Tengu no Wabi Shoumon', 2, 'Touhou Project Arrangements Pack 4', False),
    ('I', 1, 'Touhou Project Arrangements Pack 4', False),
    ('Keep the Faith', 2, 'Touhou Project Arrangements Pack 4', False),
    ('Foughten Field', 2, 'Touhou Project Arrangements Pack 4', False),
    ('ケロ⑨destiny Kero 9 destiny', 2, 'Touhou Project Arrangements Pack 4', True),
    ("Spider's Blood", 2, 'Touhou Project Arrangements Pack 5', False),
    ('無間嫉妬劇場『666』 NetaminityTheater「666」', 1, 'Touhou Project Arrangements Pack 5', False),
    ('大江山ジャイアントスイング OEYAMA Giant Swing', 2, 'Touhou Project Arrangements Pack 5', False),
    ('鼓動、零れぬ酒 Kodou, Koborenu Sake', 2, 'Touhou Project Arrangements Pack 5', False),
    ('サトリアイ Satori Eye (feat. ｙｔｒ)', 2, 'Touhou Project Arrangements Pack 5', False),
    ('BlazeConductor', 2, 'Touhou Project Arrangements Pack 5', False),
    ('カミノヒ KAMINOHI', 1, 'Touhou Project Arrangements Pack 5', False),
    ('お空のニュークリア フュージョン道場 Okuu no Nuclear Fusion Dojo', 1, 'Touhou Project Arrangements Pack 5', False),
    ('カリソメ KARISOME', 2, 'Touhou Project Arrangements Pack 5', False),
    ('東方双地舞 Touhou Souchimai', 2, 'Touhou Project Arrangements Pack 5', True),
    ('仙酌絶唱のファンタジア Sensyaku Zeshou No Fantasia', 2, 'Touhou Project Arrangements Pack 6', False),
    ('IMAGINA', 1, 'Touhou Project Arrangements Pack 6', False),
    ('君色Petal kimiiro Petal', 2, 'Touhou Project Arrangements Pack 6', False),
    ('ピュアヒューリーズ Pure Furies -YS MIX-', 1, 'Touhou Project Arrangements Pack 6', False),
    ('ロストワードクロニカル Lost Word Chronicle', 2, 'Touhou Project Arrangements Pack 6', False),
    ('ホイホイ☆幻想ホロイズム Hoi Hoi ☆ Genso Holoism', 3, 'Touhou Project Arrangements Pack 6', False),
    ('シアワセうさぎ・ ぺこみこマリン Shiawase Usagi, PekoMikoMarine', 1, 'Touhou Project Arrangements Pack 6', False),
    ('幻想に咲いた花 A flower blooming on phantasm', 2, 'Touhou Project Arrangements Pack 6', False),
    ('マツヨイナイトバグ MATSUYOI Nightbug', 3, 'Touhou Project Arrangements Pack 6', False),
    ('東方音銃夢 Touhou Onganmu', 3, 'Touhou Project Arrangements Pack 6', True),
    ('スカーレット警察の ゲットーパトロール24時 Scarlet Police Getto Patrol 24 hour', 2, 'Touhou Project Arrangements Pack 7', False),
    ('No Life Queen [DJ Command Remix]', 2, 'Touhou Project Arrangements Pack 7', False),
    ('Who Killed U.N.Owen', 3, 'Touhou Project Arrangements Pack 7', False),
    ('細い線 Hosoi sen', 4, 'Touhou Project Arrangements Pack 7', False),
    ('東方散楽祭 Touhou Sangakusai', 4, 'Touhou Project Arrangements Pack 7', False),
    ('ってゐ！ ～えいえんてゐver.～ Ttewi -Eientewi ver.-', 3, 'Touhou Project Arrangements Pack 7', False),
    ('患部で止まってすぐ溶ける ～狂気の優曇華院 Kanbu de Tomatte sugu Tokeru Kyoki no Udongein', 2, 'Touhou Project Arrangements Pack 7', False),
    ('Cruel Moon NuMIX', 2, 'Touhou Project Arrangements Pack 7', False),
    ('囲い無き世は一期の月影 Kakoi naki yo ha ichigo no tsukikage', 3, 'Touhou Project Arrangements Pack 7', False),
    ('境界の宴 Feast of the Boundary', 2, 'Touhou Project Arrangements Pack 7', True),
    ('マウストゥーマウス Mouth to mouth', 2, 'Touhou Project Arrangements Pack 8', False),
    ('パラソルメモリーズ Parasol Memories', 2, 'Touhou Project Arrangements Pack 8', False),
    ('ハシル Hashiru', 2, 'Touhou Project Arrangements Pack 8', False),
    ('Endless Seeker', 2, 'Touhou Project Arrangements Pack 8', False),
    ('ゲキツイムラサ Gekitsui Murasa', 3, 'Touhou Project Arrangements Pack 8', False),
    ('あいつはイカサマをしている Aitsu Wa Ikasama Wo Shiteiru', 2, 'Touhou Project Arrangements Pack 8', False),
    ('Sad Rain', 1, 'Touhou Project Arrangements Pack 8', False),
    ('FOUR SEASONS OF LONELINESS verβ feat.サリヤ人(Sariyajin)', 3, 'Touhou Project Arrangements Pack 8', False),
    ('未確認幻想コースター Mikakunin Gensou Coaster', 2, 'Touhou Project Arrangements Pack 8', False),
    ('東方星連戦 Touhou Seirensen', 4, 'Touhou Project Arrangements Pack 8', True),
    ('緋色月下、狂咲ノ絶 Hiirogekka, Kyoushounozetsu 15th Anniversary Remix nayuta.ver', 2, 'Touhou Project Arrangements Pack 9', False),
    ('東方不死鳥 Touhou Fushichou', 3, 'Touhou Project Arrangements Pack 9', False),
    ('天狗の落とし文 Tengu no Otoshibumi feat. y t r', 2, 'Touhou Project Arrangements Pack 9', False),
    ('Calamity Fortune', 4, 'Touhou Project Arrangements Pack 9', False),
    ('コノハズク Konohazuku', 2, 'Touhou Project Arrangements Pack 9', False),
    ('サドマミホリック Sado Mami Holic', 3, 'Touhou Project Arrangements Pack 9', False),
    ('九十九星降 Tsukumo Seikou', 2, 'Touhou Project Arrangements Pack 9', False),
    ('Dream Coaster', 2, 'Touhou Project Arrangements Pack 9', False),
    ('東方外魔伝 Touhou Gaimaden', 3, 'Touhou Project Arrangements Pack 9', True),
    ('ダイナマイト Dynamite', 3, 'Touhou Project Arrangements Pack 9', False),
    ("Frey's Philosophy", 2, 'Lanota Pack', False),
    ('Journey', 3, 'Lanota Pack', False),
    ('cyanine', 2, 'Lanota Pack', False),
    ('Apocalypse', 1, 'Lanota Pack', False),
    ('Song for Sprites', 1, 'Lanota Pack', False),
    ('Androgynos', 2, 'Lanota Pack', False),
    ('You are the Miserable', 3, 'Lanota Pack', False),
    ('Hayabusa', 2, 'Lanota Pack', False),
    ('Specta', 3, 'Lanota Pack', False),
    ('MariannE (Lanota Edit)', 2, 'Lanota Pack', True),
    ('glory day', 3, 'DJMAX RESPECT Pack', False),
    ('OBLIVION', 2, 'DJMAX RESPECT Pack', False),
    ('U.A.D', 3, 'DJMAX RESPECT Pack', False),
    ("Don't Die", 3, 'DJMAX RESPECT Pack', False),
    ('Ray of Illuminati', 4, 'DJMAX RESPECT Pack', True),
    ('Nevermind', 4, 'DJMAX RESPECT Pack', False),
    ('Thor(DJMAX)', 3, 'DJMAX RESPECT Pack', False),
    ('SON OF SUN', 3, 'DJMAX RESPECT Pack', False),
    ('Fermion', 2, 'DJMAX RESPECT Pack', False),
    ('I want You', 1, 'DJMAX RESPECT Pack', False),
    ('Lights of Muse', 1, 'Muse Dash + Misc Pack', False),
    ('Stargazer', 1, 'Muse Dash + Misc Pack', False),
    ('XING', 2, 'Muse Dash + Misc Pack', False),
    ('粉骨砕身カジノゥ Funkotsu Saishin Casinou', 3, 'Muse Dash + Misc Pack', False),
    ('Gift box', 2, 'Muse Dash + Misc Pack', False),
    ('ЯUBY:LINTe', 3, 'Muse Dash + Misc Pack', False),
    ('Altale', 1, 'Muse Dash + Misc Pack', False),
    ('GOODBOUNCE', 2, 'Muse Dash + Misc Pack', False),
    ('プナイプナイたいそう Punai Punai Taisou', 3, 'Muse Dash + Misc Pack', False),
    ('MilK', 1, 'Muse Dash + Misc Pack', True),
    ('Let you DIVE!', 2, 'WACCA + HARDCORE TANO*C Pack', False),
    ('Gate One', 2, 'WACCA + HARDCORE TANO*C Pack', False),
    ('Poseidon', 4, 'WACCA + HARDCORE TANO*C Pack', False),
    ('Knight Rider', 4, 'WACCA + HARDCORE TANO*C Pack', False),
    ('Invisible Frenzy', 4, 'WACCA + HARDCORE TANO*C Pack', True),
    ('with U', 2, 'WACCA + HARDCORE TANO*C Pack', False),
    ('Ever Free', 1, 'WACCA + HARDCORE TANO*C Pack', False),
    ('Sound Chimera', 3, 'WACCA + HARDCORE TANO*C Pack', False),
    ('Shiny Memory feat. Yukacco', 2, 'WACCA + HARDCORE TANO*C Pack', False),
    ('RAV#GIRL', 3, 'WACCA + HARDCORE TANO*C Pack', False),
    ('Ignotus', 2, 'Arcaea + Misc Pack', False),
    ('Be There', 3, 'Arcaea + Misc Pack', False),
    ('Metallic Punisher', 3, 'Arcaea + Misc Pack', False),
    ('Modelista', 2, 'Arcaea + Misc Pack', False),
    ('Singularity', 4, 'Arcaea + Misc Pack', False),
    ('Corruption', 3, 'Arcaea + Misc Pack', False),
    ('Grievous Lady', 5, 'Arcaea + Misc Pack', False),
    ('Black Lotus', 4, 'Arcaea + Misc Pack', False),
    ('GOODTEK', 3, 'Arcaea + Misc Pack', False),
    ('First Snow', 1, 'Arcaea + Misc Pack', True),
    ('Legend of Moonlight', 2, 'EZ2ON REBOOT:R Pack', False),
    ('The Prince of Darkness', 2, 'EZ2ON REBOOT:R Pack', False),
    ('神威 Kamui', 5, 'EZ2ON REBOOT:R Pack', True),
    ('ApolloN', 3, 'EZ2ON REBOOT:R Pack', False),
    ('A Site De La Rue', 2, 'EZ2ON REBOOT:R Pack', False),
    ('sweet★star', 2, 'EZ2ON REBOOT:R Pack', False),
    ('WE ALIVE', 2, 'EZ2ON REBOOT:R Pack', False),
    ('picking', 3, 'EZ2ON REBOOT:R Pack', False),
    ('Daydream', 4, 'EZ2ON REBOOT:R Pack', False),
    ('Hi-TECH Soda Machine', 1, 'EZ2ON REBOOT:R Pack', False),
    ('Skyfall', 2, 'CHRONO CIRCLE + Tetote Connect Pack', False),
    ('futuristic clock', 4, 'CHRONO CIRCLE + Tetote Connect Pack', True),
    ('PAPAN!ベリーラブ！ PAPAN! Very Love!', 2, 'CHRONO CIRCLE + Tetote Connect Pack', False),
    ('SUPER ☆HARAGURO☆POP', 2, 'CHRONO CIRCLE + Tetote Connect Pack', False),
    ('SKYDAZE', 3, 'CHRONO CIRCLE + Tetote Connect Pack', False),
    ('キミとのテトテコネクト A Tetocone With You', 1, 'CHRONO CIRCLE + Tetote Connect Pack', False),
    ('紅色パラソル Beniiro Parasol feat. Yukacco', 2, 'CHRONO CIRCLE + Tetote Connect Pack', False),
    ('フレテミタイ FURETE-MITAI', 1, 'CHRONO CIRCLE + Tetote Connect Pack', False),
    ('手と手合わせて Tetote Awasete', 2, 'CHRONO CIRCLE + Tetote Connect Pack', False),
    ('edge//lord', 2, 'CHRONO CIRCLE + Tetote Connect Pack', False),
    ('Hurt Land', 2, 'CHRONO CIRCLE + MUSIC DIVER Pack', False),
    ('No More Grief', 2, 'CHRONO CIRCLE + MUSIC DIVER Pack', False),
    ('Midnight Scramble', 3, 'CHRONO CIRCLE + MUSIC DIVER Pack', False),
    ("セピアと白昼夢 Sepia's Daydream", 2, 'CHRONO CIRCLE + MUSIC DIVER Pack', False),
    ('AMiDARA PIERROT', 1, 'CHRONO CIRCLE + MUSIC DIVER Pack', False),
    ('MUSIC DIVE!!', 2, 'CHRONO CIRCLE + MUSIC DIVER Pack', False),
    ('shrink', 2, 'CHRONO CIRCLE + MUSIC DIVER Pack', False),
    ('薔薔薔薇薔薇薔薔薇 Bababarabarababara', 1, 'CHRONO CIRCLE + MUSIC DIVER Pack', False),
    ('HYPER SAMPLER', 2, 'CHRONO CIRCLE + MUSIC DIVER Pack', False),
    ('Metaverse Do Be Like This', 4, 'CHRONO CIRCLE + MUSIC DIVER Pack', True),
    ('VERTeX', 5, 'maimai DX + ONGEKI Pack', False),
    ('Aiolos', 4, 'maimai DX + ONGEKI Pack', False),
    ('福宿音屋魂音泉 FUKUYADORU OTOYA "TAMAYONSEN"', 2, 'maimai DX + ONGEKI Pack', False),
    ('TEmPTaTiON', 3, 'maimai DX + ONGEKI Pack', True),
    ('ツムギボシ TSUMUGIBOSHI', 2, 'maimai DX + ONGEKI Pack', False),
    ('MEGATON BLAST', 3, 'maimai DX + ONGEKI Pack', False),
    ('Singularity', 4, 'maimai DX + ONGEKI Pack', False),
    ('Elusive Emotes', 3, 'maimai DX + ONGEKI Pack', False),
    ('Magical Panic Adventure', 4, 'maimai DX + ONGEKI Pack', False),
    ('Island Breeze', 2, 'maimai DX + ONGEKI Pack', False),
    ('怒槌 Ikazuchi', 3, 'CHUNITHM Pack', False),
    ('Paqqin', 2, 'CHUNITHM Pack', False),
    ('眠れぬ夜君を想フ Nemurenuyo Kimiwo omofu', 3, 'CHUNITHM Pack', False),
    ('World Vanquisher', 4, 'CHUNITHM Pack', False),
    ('Xevel', 3, 'CHUNITHM Pack', False),
    ('Summer is over', 3, 'CHUNITHM Pack', False),
    ('Nijirate Fanatics', 4, 'CHUNITHM Pack', True),
    ('Trrricksters!!', 3, 'CHUNITHM Pack', False),
    ('コスモポップファンクラブ Cosmo Pop Funclub', 2, 'CHUNITHM Pack', False),
    ('雪男 YukiOtoko', 5, 'CHUNITHM Pack', False),
    ('Bonetrousle', 1, 'UNDERTALE Pack', False),
    ('正義の槍 Spear of Justice', 2, 'UNDERTALE Pack', False),
    ('スパイダーダンス Spider Dance', 3, 'UNDERTALE Pack', False),
    ('華麗なる死闘 Death by Glamour', 2, 'UNDERTALE Pack', False),
    ('アズゴア ASGORE', 1, 'UNDERTALE Pack', False),
    ('最高の悪夢 Your Best Nightmare', 3, 'UNDERTALE Pack', False),
    ('これでホントにサヨナラ Last Goodbye', 2, 'UNDERTALE Pack', False),
    ('本物のヒーローとの戦い Battle Against a True Hero', 2, 'UNDERTALE Pack', False),
    ('MEGALOVANIA', 5, 'UNDERTALE Pack', False),
    ('THE WORLD REVOLVING', 3, 'UNDERTALE Pack', True),
    ('ナムコットメドレー NAMCOT Medley', 3, 'Game Song Pack', False),
    ('KAGEKIYO 源平討魔伝メドレー "The Genji and the Heike Clans" Medley', 2, 'Game Song Pack', False),
    ('ドラゴンスピリットメドレー DRAGON SPIRIT Medley', 4, 'Game Song Pack', False),
    ('Penetration of light into morality', 2, 'Game Song Pack', False),
    ('ON THE VERGE OF REVIVAL (RED HARDCORE REMIX)', 2, 'Game Song Pack', False),
    ('Shadow', 4, 'Game Song Pack', True),
    ('Twister -Final Remix-', 1, 'Game Song Pack', False),
    ('サムデイ Someday', 2, 'Game Song Pack', False),
    ('NEW GAME', 4, 'Game Song Pack', False),
    ('LAST CALL', 2, 'Game Song Pack', False),
    ('怒りのマネキン！ Dummy!', 2, 'UNDERTALE+DELTARUNE Pack', False),
    ('コア CORE', 3, 'UNDERTALE+DELTARUNE Pack', False),
    ('手ミーむら！/手ミーみせ！ Temmie Village / Tem Shop', 3, 'UNDERTALE+DELTARUNE Pack', False),
    ('夢と希望 Hopes and Dreams', 2, 'UNDERTALE+DELTARUNE Pack', False),
    ('ルードバスター Rude Buster', 2, 'UNDERTALE+DELTARUNE Pack', False),
    ('夢と希望の平原 Field of Hopes and Dreams', 1, 'UNDERTALE+DELTARUNE Pack', False),
    ('カオスの王 Chaos King', 2, 'UNDERTALE+DELTARUNE Pack', False),
    ("CYBER WORLD A CYBER'S WORLD?", 2, 'UNDERTALE+DELTARUNE Pack', False),
    ('進撃のキラークイーン Attack of the Killer Queen', 2, 'UNDERTALE+DELTARUNE Pack', False),
    ('[[BIGの力 BIG SHOT]]', 1, 'UNDERTALE+DELTARUNE Pack', True),
    ('カラフルビート Colorful Beat', 2, 'HARDCORE TANO*C Pack', False),
    ('VELVET', 2, 'HARDCORE TANO*C Pack', False),
    ('Good Night, Bad Luck.', 5, 'HARDCORE TANO*C Pack', False),
    ('CrossFire', 4, 'HARDCORE TANO*C Pack', False),
    ('NEUTRON SANDBOX', 4, 'HARDCORE TANO*C Pack', False),
    ('Old Heaven', 2, 'HARDCORE TANO*C Pack', False),
    ('Enhancer (Light in the air)', 3, 'HARDCORE TANO*C Pack', False),
    ('アカツキノソラ Dawning Sky (feat. DELUTAYA)', 2, 'HARDCORE TANO*C Pack', False),
    ('ミラクルポップ ☆ アドベンチャー!!!!! Miracle Pop☆Adventure!!!!!', 4, 'HARDCORE TANO*C Pack', False),
    ('BATTLE NO.1', 3, 'HARDCORE TANO*C Pack', True),
    ('GLITHCRE', 4, 'Original Pack', True),
    ('DX超性能フルメタル少女 DX Choseinou Full Metal Shojo', 4, 'Original Pack', False),
    ('MIRACLE PARTY', 3, 'Original Pack', False),
    ('Xand-Roid', 4, 'Original Pack', False),
    ('HAPPY! LUCKY! FUTURE WORLD!', 3, 'Original Pack', False),
    ('QLWA', 2, 'Original Pack', False),
    ('MAD FREAKS', 3, 'Original Pack', False),
    ('Little Higher', 2, 'Original Pack', False),
    ('MOVING FASTER FT. LINDSEY MARIE', 2, 'Original Pack', False),
    ('Cosmic Express', 3, 'Original Pack', False),
    ('Gimme吟味virtuaる最高star!!!! Gimme gimme virtuaL saikou star!!!', 2, 'Original Pack 2', False),
    ('グルーヴ・ザ・ハート GROOVE THE HEART', 2, 'Original Pack 2', False),
    ('Caramel Mocha', 1, 'Original Pack 2', False),
    ('Under The Moon', 2, 'Original Pack 2', False),
    ('座和々 Zawawa', 2, 'Original Pack 2', False),
    ('PUT YOUR HANDS UP', 2, 'Original Pack 2', False),
    ('全人類犬化計画 Zenjinrui Inuka Keikaku', 2, 'Original Pack 2', False),
    ('Aurgelmir', 4, 'Original Pack 2', False),
    ('FUJIN Rumble', 4, 'Original Pack 2', False),
    ('Marry me, Nightmare', 6, 'Original Pack 2', True),
    ('OVER THE NIGHT', 2, 'Original Pack 3', False),
    ('SKYSCRAPER', 3, 'Original Pack 3', False),
    ('Groove Prayer', 2, 'Original Pack 3', False),
    ('HG魔改造ポリビニル少年 HG Makaizou Polyvinyl Shounen', 2, 'Original Pack 3', False),
    ('JUMPEE!', 3, 'Original Pack 3', False),
    ('平成快晴どってんしゃん Heisei Kaisei Dottensyan', 4, 'Original Pack 3', False),
    ('APELIOTES', 2, 'Original Pack 3', False),
    ('Apocalypse Lotus', 5, 'Original Pack 3', False),
    ('Third Time UNLucky', 6, 'Original Pack 3', False),
    ('セイレーンの邀撃 Interceptor of SIREN', 5, 'Original Pack 3', True),
    ('聖者の鼓動 Seizya no Kodo', 2, 'Original Pack 4 (10th Anniversary)', False),
    ('Satisfiction', 1, 'Original Pack 4 (10th Anniversary)', False),
    ('AM貴族 すたどんたん殿下 AM Kizoku Sutadontan Denka', 3, 'Original Pack 4 (10th Anniversary)', False),
    ('熟成!醸造!発酵星◎ ～スペースヨーグルアース～ Jukusei Jozo Hakkosei◎ -Space Yogurt Earth-', 5, 'Original Pack 4 (10th Anniversary)', False),
    ('まよなかのヒミツ The secrets of ghosts', 4, 'Original Pack 4 (10th Anniversary)', False),
    ('#AKKAN_BABY', 2, 'Original Pack 4 (10th Anniversary)', False),
    ('ツートン・アドベンチャー Adventure for Two Tones', 2, 'Original Pack 4 (10th Anniversary)', False),
    ('Moonflare', 2, 'Original Pack 4 (10th Anniversary)', False),
    ('Cryptocurrency Billionaire', 5, 'Original Pack 4 (10th Anniversary)', False),
    ('Warlock', 2, 'Original Pack 4 (10th Anniversary)', True),
    ('聖者の鼓動 Seizya no Kodo', 2, 'Original Pack 5 (10th Anniversary 2)', False),
    ('Satisfiction', 1, 'Original Pack 5 (10th Anniversary 2)', False),
    ('AM貴族 すたどんたん殿下 AM Kizoku Sutadontan Denka', 3, 'Original Pack 5 (10th Anniversary 2)', False),
    ('熟成!醸造!発酵星◎ ～スペースヨーグルアース～ Jukusei Jozo Hakkosei◎ -Space Yogurt Earth-', 5, 'Original Pack 5 (10th Anniversary 2)', False),
    ('まよなかのヒミツ The secrets of ghosts', 4, 'Original Pack 5 (10th Anniversary 2)', False),
    ('#AKKAN_BABY', 2, 'Original Pack 5 (10th Anniversary 2)', False),
    ('ツートン・アドベンチャー Adventure for Two Tones', 2, 'Original Pack 5 (10th Anniversary 2)', False),
    ('Moonflare', 2, 'Original Pack 5 (10th Anniversary 2)', False),
    ('Cryptocurrency Billionaire', 5, 'Original Pack 5 (10th Anniversary 2)', False),
    ('Warlock', 2, 'Original Pack 5 (10th Anniversary 2)', True),
    ('PIXEL STAR', 1, 'Original Pack 6 (10th Anniversary 3)', False),
    ('カンフーマスター＝拳 Kung Fu Master = Ken', 2, 'Original Pack 6 (10th Anniversary 3)', False),
    ('終わらないグルーヴ Owaranai Groove', 2, 'Original Pack 6 (10th Anniversary 3)', False),
    ('TAKING OFF', 4, 'Original Pack 6 (10th Anniversary 3)', False),
    ('Lethal Dose', 3, 'Original Pack 6 (10th Anniversary 3)', False),
    ('シンドイ・ザ・ライド SHINDOI THE RIDE', 2, 'Original Pack 6 (10th Anniversary 3)', True),
    ('Welcome to the Multiverse!', 4, 'Original Pack 6 (10th Anniversary 3)', False),
    ('漆黒獣グリモワルド GrimoireD', 3, 'Original Pack 6 (10th Anniversary 3)', False),
    ('Headshot', 2, 'Original Pack 6 (10th Anniversary 3)', False),
    ('空へ Sorae', 2, 'Original Pack 6 (10th Anniversary 3)', False),
    ('OMAKENO Stroke', 3, 'Original Pack 7', False),
    ('Got a pain cover?', 5, 'Original Pack 7', True),
    ('聖者の息吹 Seija no Ibuki', 4, 'Original Pack 7', False),
    ('tiny tales continue', 2, 'Original Pack 7', False),
    ('クレープ・to・ミー。 Crape・to・Me.', 2, 'Original Pack 7', False),
    ('アルカンシエル Arc-en-ciel', 2, 'Original Pack 7', False),
    ('∠Night Train≡☆ 銀河モーターカーの夜 Ginga Mortorcar no Yoru', 3, 'Original Pack 7', False),
    ('Far In Love', 1, 'Original Pack 7', False),
    ('influencer', 3, 'Original Pack 7', False),
    ('MUSIC OF GLORY', 4, 'Original Pack 7', False),
    ('No Way Out', 3, 'Original Pack 8 (Arcade Memorial)', False),
    ('Stardust Vox', 4, 'Original Pack 8 (Arcade Memorial)', False),
    ('HB-axeleration', 3, 'Original Pack 8 (Arcade Memorial)', False),
    ('STARLIGHT TWILIGHT -GC edit-', 2, 'Original Pack 8 (Arcade Memorial)', False),
    ('Got noir forever.', 5, 'Original Pack 8 (Arcade Memorial)', False),
    ('Solar Storm', 3, 'Original Pack 8 (Arcade Memorial)', False),
    ('Warrior', 3, 'Original Pack 8 (Arcade Memorial)', False),
    ('TAKING OFF (Massive New Krew Remix)', 2, 'Original Pack 8 (Arcade Memorial)', False),
    ('VELVET (Tatsh Remix)', 2, 'Original Pack 8 (Arcade Memorial)', False),
    ('FUJIN Rumble MASAKI Remix', 4, 'Original Pack 8 (Arcade Memorial)', True),
    ('Analysis Division', 1, 'Original Pack 9', False),
    ('グルーヴ・リボルバー Groove Revolver', 3, 'Original Pack 9', False),
    ('Five to Seven', 2, 'Original Pack 9', False),
    ('Black MInD', 3, 'Original Pack 9', False),
    ('Stratospheric Journey', 4, 'Original Pack 9', False),
    ('Scarlet Lance', 3, 'Original Pack 9', True),
    ('Unbreakable', 3, 'Original Pack 9', False),
    ('Arq Eid', 3, 'Original Pack 9', False),
    ('Flower Princess', 2, 'Original Pack 9', False),
    ('陌獸戰爭 War against the Eldritch Beasts', 5, 'Original Pack 9', False),
    ('ouroboros -twin stroke of the end-', 5, 'Original Pack 10 (Final Boss)', False),
    ('Crimson Phoenix', 3, 'Original Pack 10 (Final Boss)', False),
    ('BUCHiGiRE Berserker', 4, 'Original Pack 10 (Final Boss)', False),
    ('Lemegeton -little key of solomon-', 5, 'Original Pack 10 (Final Boss)', False),
    ('QiXiN MAdN3ss 2153', 5, 'Original Pack 10 (Final Boss)', False),
    ('神 KAMI', 5, 'Original Pack 10 (Final Boss)', False),
    ('Got a over score?', 5, 'Original Pack 10 (Final Boss)', True),
    ('Athena', 4, 'Original Pack 10 (Final Boss)', False),
    ('Cait Sith Carnival', 5, 'Original Pack 10 (Final Boss)', False),
    ('AMA', 5, 'Original Pack 10 (Final Boss)', False),
    ('Future Diver', 3, 'Dempagumi.inc Pack', True),
    ('でんぱれーどJAPAN Demparade Japan', 2, 'Dempagumi.inc Pack', False),
    ('W.W.D', 5, 'Dempagumi.inc Pack', False),
    ('でんでんぱっしょん Denden Passion', 5, 'Dempagumi.inc Pack', False),
    ('サクラあっぱれーしょん Sakura Appareshon', 1, 'Dempagumi.inc Pack', False),
    ('ちゅるりちゅるりら Chururi Chururira', 3, 'Dempagumi.inc Pack', False),
    ('でんぱーりーナイト Demparty Night', 2, 'Dempagumi.inc Pack', False),
    ('おつかれサマー！ Otsukare Summer', 1, 'Dempagumi.inc Pack', False),
    ('Ψ発見伝！ Psi Hakkenden!', 2, 'Dempagumi.inc Pack', False),
    ('プレシャスサマー！ Precious Summer', 3, 'Dempagumi.inc Pack', False),
]

# Archipelago Options

class DragorrodsGrooveCoasterWaiWaiPartyIncludedDLC(OptionSet):
    """
    Indicates which Groove Coaster Wai Wai Party!!!! DLC packs are owned and can be pulled from.

    Songs belonging to a DLC pack that is not selected here will not be used.
    """

    display_name = "Dragorrod's Groove Coaster Wai Wai Party Included DLC"

    valid_keys = frozenset(
        {
            'Arcaea + Misc Pack',
            'CHRONO CIRCLE + MUSIC DIVER Pack',
            'CHRONO CIRCLE + Tetote Connect Pack',
            'CHUNITHM Pack',
            'D4DJ Groovy Mix + Game Song Pack',
            'DJMAX RESPECT Pack',
            'Dempagumi.inc Pack',
            'EZ2ON REBOOT:R Pack',
            'Game Song Pack',
            'HARDCORE TANO*C Pack',
            'Hit Song + VTuber Pack',
            'Hit Song + VTuber Pack 2',
            'Hit Song + VTuber Pack 3',
            'Hit Song + VTuber Pack 4',
            'Hit Song + VTuber Pack 5',
            'Hit Song + VTuber Pack 6',
            'Lanota Pack',
            'Muse Dash + Misc Pack',
            'Original Pack',
            'Original Pack 10 (Final Boss)',
            'Original Pack 2',
            'Original Pack 3',
            'Original Pack 4 (10th Anniversary)',
            'Original Pack 5 (10th Anniversary 2)',
            'Original Pack 6 (10th Anniversary 3)',
            'Original Pack 7',
            'Original Pack 8 (Arcade Memorial)',
            'Original Pack 9',
            'Touhou Project Arrangements Pack 1',
            'Touhou Project Arrangements Pack 2',
            'Touhou Project Arrangements Pack 3',
            'Touhou Project Arrangements Pack 4',
            'Touhou Project Arrangements Pack 5',
            'Touhou Project Arrangements Pack 6',
            'Touhou Project Arrangements Pack 7',
            'Touhou Project Arrangements Pack 8',
            'Touhou Project Arrangements Pack 9',
            'UNDERTALE Pack',
            'UNDERTALE+DELTARUNE Pack',
            'VOCALOID Pack',
            'VOCALOID Pack 2',
            'VOCALOID Pack 3',
            'VOCALOID Pack 4',
            'VOCALOID Pack 5',
            'VOCALOID Pack 6',
            'VOCALOID Pack 7',
            'VOCALOID Pack 8',
            'VOCALOID Pack 9',
            'WACCA + HARDCORE TANO*C Pack',
            'hololive Pack',
            'hololive Pack 2',
            'maimai DX + ONGEKI Pack'
        }
    )

    default = valid_keys


class DragorrodsGrooveCoasterWaiWaiPartyIncludeMissionLockedSongs(Toggle):
    """
    Indicates whether songs that must be unlocked via a Song Mission (base game) or by playing all
    the songs in their pack (DLC) can be included.
    """

    display_name = "Dragorrod's Groove Coaster Wai Wai Party Include Mission Locked Songs"
